export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as Banner} from './Banner'
export {default as Banner1} from './Banner1'
export {default as Product} from './Product'